### ISSUE TITLE
Use JSON

### ISSUE THREAD

**Issue by evantahler** [queue-bus/queue-bus#2]
in the current version of resque bus, the subscriptions are stored as ruby hashes. We should move to JSON so other languages don't have such a hard time integrating.  For example, here's how we attempt to do this in node: https://github.com/taskrabbit/node-resquebus/blob/master/lib/sections/utils.js (madness)

Resque in general speaks JSON for the queues etc. This would be consistent.

**Comment by bleonard** [comment]
It would have to be stored as a "string" as far as resque/sidekiq was concerned. Then each worker would have to decode it. We could probably make some helpers to do that.

With the change to queue-bus, this would be a good time to do it. We'll be queueing up `QueueBus::Rider` and friends now. Those could always assume the JSON situation. We're going to have to port over `ResqueBus::Rider` and friends so there's no errors on transition anyway. Those could extend their counterparts and convert over from the ruby hashes.

**Comment by evantahler** [comment]
Huzzah!
