### ISSUE TITLE
NameError: uninitialized constant Forwardable

### ISSUE THREAD

**Issue by ryanscott** [queue-bus/queue-bus#5]
With Ruby 2.2.1, I get the following error on `rake queuebus:subscribe`

rake aborted!
NameError: uninitialized constant Module::Forwardable
/Users/ryan/.rvm/gems/ruby-2.2.1@neeson/gems/queue-bus-0.5.5/lib/queue-bus.rb:31:in `singleton class'
/Users/ryan/.rvm/gems/ruby-2.2.1@neeson/gems/queue-bus-0.5.5/lib/queue-bus.rb:28:in `<module:QueueBus>'
/Users/ryan/.rvm/gems/ruby-2.2.1@neeson/gems/queue-bus-0.5.5/lib/queue-bus.rb:3:in `<top (required)>'
/Users/ryan/.rvm/gems/ruby-2.2.1@neeson/gems/queue-bus-0.5.5/lib/queue_bus/tasks.rb:30:in `block (2 levels) in <top (required)>'
Tasks: TOP => queuebus:subscribe => queuebus:preload

`queue-bus.rb` seems to need `require 'forwardable'` and that solves the issue.  I'll submit a PR.

Relevant same issue for resque (great explanation at the bottom.  TLDR: bundler requires `forwardable`, so the tests pass): https://github.com/resque/resque/issues/1128

**Comment by bleonard** [comment]
is it the case we just need to `require 'forwardable'`?
Do you know if that has issues when < 2.2 ?

**Comment by ryanscott** [comment]
Yes, adding `require forwardable` solves the problem (both for queue-bus and for the other repos I've seen this problem).

Adding the require causes no problems on ruby 1.9.3 or 2.2.1, so I assume versions in between will be ok, but I've only tested those 2 versions.

**Comment by fleas** [comment]
same issue pretty much ubuntu 14.04 LTS

/opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pghero'. (Bundler::GemRequireError)
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /opt/pghero/config/application.rb:2:in `<top (required)>'
	from /opt/pghero/config/environment.rb:2:in `require'
	from /opt/pghero/config/environment.rb:2:in `<top (required)>'
	from config.ru:3:in `require'
	from config.ru:3:in `block in <main>'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:370:in `run'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/bin/puma:23:in `load'
	from /opt/pghero/vendor/bundle/ruby/2.3.0/bin/puma:23:in `<main>'

I even attempted to use the latest pghero gem. I set my path to:
usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/pghero/vendor/ruby-2.3.1/bin:/usr/local/sbin:/usr/local/bin

no luck .

root@ip-172-30-0-198:/opt/pghero/vendor/ruby-2.3.1/bin# irb
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> require 'forwardable'
=> true
irb(main):003:0> require 'pghero'
=> true

**Comment by Callisto7** [comment]
`<top (required)>': uninitialized
